apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: nfs-provisioner-01
      meta.helm.sh/release-namespace: nfs-provisioner
    creationTimestamp: "2023-06-05T11:24:02Z"
    generation: 1
    labels:
      app: nfs-subdir-external-provisioner
      app.kubernetes.io/managed-by: Helm
      chart: nfs-subdir-external-provisioner-4.0.18
      heritage: Helm
      release: nfs-provisioner-01
    name: nfs-provisioner-01-nfs-subdir-external-provisioner
    namespace: nfs-provisioner
    resourceVersion: "93723"
    uid: 37a09e83-aa8c-4059-980b-0b8968dcb252
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: nfs-subdir-external-provisioner
        release: nfs-provisioner-01
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: nfs-subdir-external-provisioner
          release: nfs-provisioner-01
      spec:
        containers:
        - env:
          - name: PROVISIONER_NAME
            value: nfs-provisioner-01
          - name: NFS_SERVER
            value: 192.168.56.111
          - name: NFS_PATH
            value: /exports/PVs
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          imagePullPolicy: IfNotPresent
          name: nfs-subdir-external-provisioner
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /persistentvolumes
            name: nfs-subdir-external-provisioner-root
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: nfs-provisioner-01-nfs-subdir-external-provisioner
        serviceAccountName: nfs-provisioner-01-nfs-subdir-external-provisioner
        terminationGracePeriodSeconds: 30
        volumes:
        - name: nfs-subdir-external-provisioner-root
          nfs:
            path: /exports/PVs
            server: 192.168.56.111
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-06-05T11:24:30Z"
      lastUpdateTime: "2023-06-05T11:24:30Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-06-05T11:24:02Z"
      lastUpdateTime: "2023-06-05T11:24:30Z"
      message: ReplicaSet "nfs-provisioner-01-nfs-subdir-external-provisioner-697f8789d5"
        has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
